### PR TITLE
remove has dependency

### PR DESCRIPTION
**Pull request by Uzlopak**

### CODE REVIEW

**Review by ljharb — CHANGES_REQUESTED** [review]
Why? `has` is a very commonly used dep that does the right thing.

**Comment by ljharb** [comment]
Note that fewer dependencies is never inherently better.

**Comment by Uzlopak** [comment]
Well if you check it is basically just a Object.prototype.hasOwnProperty wrapper without any polyfill/ponyfill/shim.

**Comment by Uzlopak** [comment]
Closing because i have already over 800+ open PRs. No interest in filling the list of open PRs further.

**Pull request closed without merging**
